# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='books',
            new_name='books_id',
        ),
    ]
